create database msims;
use msims;

drop table user;
# General table
CREATE TABLE user (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userId VARCHAR(20) NOT NULL UNIQUE,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(32) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    faculty VARCHAR(20) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    roles VARCHAR(255) NOT NULL,
    salt VARCHAR(32) NOT NULL
)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;


CREATE TABLE course (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    courseCode VARCHAR(20) NOT NULL,
    faculty varchar(20) not null,
    name VARCHAR(50) NOT NULL,
    credit INT(2) NOT NULL,
    teacher VARCHAR(100) NOT NULL,
    duration VARCHAR(100) NOT NULL,
    time VARCHAR(255) NOT NULL,
    description TEXT NOT NULL
)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;

CREATE TABLE file (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fileId VARCHAR(32) NOT NULL,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL
)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;

# Moddle tables
create table student_course(
	id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userId VARCHAR(20) NOT NULL,
    courseCode VARCHAR(20) NOT NULL
) ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;

CREATE TABLE component (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    courseCode VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL
)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;

CREATE TABLE component_file (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    componentId INT(20) NOT NULL,
    fileId VARCHAR(32) NOT NULL
)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;

CREATE TABLE bulletin_board (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    courseCode VARCHAR(20) NOT NULL
)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;

CREATE TABLE bulletin_board_message (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    boardIdcomponent_file INT(20) NOT NULL,
    content text NOT NULL,
    date VARCHAR(20) NOT NULL
)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;

CREATE TABLE comment (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    courseCode VARCHAR(20) NOT NULL,
    pid INT(20) NOT NULL,
    commenterId INT(20) NOT NULL,
    respondentId INT(20) NOT NULL,
    content TEXT NOT NULL,
    type VARCHAR(20) NOT NULL,
    date VARCHAR(20) NOT NULL
)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;

#CREATE TABLE  (
    
#)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;

CREATE TABLE submission (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(20) NOT NULL,
    description VARCHAR(20) NOT NULL,
    submissionStatus VARCHAR(20) NOT NULL,
    gradingStatus VARCHAR(20) NOT NULL,
    dueStatus VARCHAR(20) NOT NULL,
    lastModified VARCHAR(20) NOT NULL,
    fileId VARCHAR(32) NOT NULL,
    submissionFileId VARCHAR(20) NOT NULL,
    comment text NOT NULL
)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;

CREATE TABLE assessment (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    submissionId INT(20) NOT NULL,
    score DOUBLE(5 , 2 ) NOT NULL,
    comment TEXT NOT NULL
)  ENGINE=INNODB , AUTO_INCREMENT=1 , CHARSET=UTF8;







